version: "3.9"
services:
  scheduler_app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${SQL_DATABASE}
      - MYSQL_USER=${SQL_USERNAME}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
    volumes:
      - mysql-db-scheduler-app:/var/lib/mysql
volumes:
  mysql-db-scheduler-app:
